# Default values for my-voting-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# adding 1 more replica
replicaCount: 2 # Default replica count for stateless services

# Image configurations - IMPORTANT: Update 'nag11' to your Docker Hub username
image:
  repository: docker.io/nag11 # Your Docker Hub username/organization
  tag: latest # Use 'latest' or a specific build number like '16'
  pullPolicy: IfNotPresent # Or 'Always' if you want to always pull from Docker Hub

# Service configurations for vote and result frontends
service:
  type: LoadBalancer # Options: ClusterIP, NodePort, LoadBalancer
  votePort: 5000
  resultPort: 5001

# Ingress configuration (Optional, requires Ingress Controller like Nginx/Traefik)
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: vote.example.com # Update with your desired hostname
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: result.example.com # Update with your desired hostname
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Database credentials (PostgreSQL) - Highly recommended to use secrets
database:
  user: postgres
  password: changeme # IMPORTANT: Change this to a strong password
  name: voting
  storageSize: 1Gi # PVC size for PostgreSQL data

# Resource requests and limits (Recommended for production)
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Worker specific configurations
worker:
  replicaCount: 1 # Can be scaled independently
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

# Redis specific configurations (standard image)
redis:
  image: redis:alpine
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

# Seed data service (Optional, runs once with --profile seed)
seedData:
  enabled: false # Set to true to include the seed service in your deployment
  image:
    repository: docker.io/nag11 # Your Docker Hub username/organization
    tag: latest # Use 'latest' or a specific build number
  profiles: ["seed"] # You'd enable this with `helm install --set seedData.enabled=true --set deploy.profiles=seed`
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
