apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-voting-app.fullname" . }}-result
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: result
  template:
    metadata:
      labels:
        {{- include "my-voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: result
    spec:
      containers:
        - name: result
          image: "{{ include "my-voting-app.resultImage" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
