apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-voting-app.fullname" . }}-db-pvc
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
