apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-voting-app.fullname" . }}-redis
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP # Only accessible within the cluster
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "my-voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
