apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-voting-app.fullname" . }}-result
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.resultPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
