{{- if .Values.seedData.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "my-voting-app.fullname" . }}-seed-data
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed-data
spec:
  template:
    metadata:
      labels:
        {{- include "my-voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: seed-data
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed-data
          image: "{{ include "my-voting-app.seedDataImage" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VOTE_URL
              value: "http://{{ include "my-voting-app.fullname" . }}-vote" # Access vote service by internal cluster DNS
          resources:
            {{- toYaml .Values.seedData.resources | nindent 12 }}
{{- end }}
