apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-voting-app.fullname" . }}-db-secret
  labels:
    {{- include "my-voting-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.database.name | b64enc | quote }}
